---
title: "Results_Overview"
output:
  pdf_document: default
  html_document: default
---

## Progress Update:

[To be filled in]

```{r setup, include=FALSE}
# my_plot_hook <- function(x, options)
#   paste("\n", knitr::hook_plot_tex(x, options), "\n")
# knitr::knit_hooks$set(plot = my_plot_hook)
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
library(tidyverse)
library(openxlsx)
library(gets)
library(getspanel)
library(here)
library(doParallel)

source(here("code/dicts.R"))
models <- readRDS(here("output/edgar_v7_models_all.RDS")) %>% 
  rbind(readRDS(here("output/edgar_v7_EU15_plus.RDS")))

for_models <- readRDS(here("output/edgar_v7_EU15_plus_formulas.RDS")) %>% arrange(p_val) %>% 
  mutate(controls = case_when(grepl("~ lgdp + lpop + lgdp_sq + HDD16dailybypop + CDD18dailybypop", source, fixed = TRUE) ~ "w/ Temp Controls",
                          grepl("~ lpop + HDD16dailybypop + CDD18dailybypop", source, fixed = TRUE) ~ "Temp & Pop Only",
                          TRUE ~ "Standard Controls"),
                        func = case_when(grepl("^l_edgar_v7", source) ~ "Levels",
                        grepl("^d.l_edgar_v7", source) ~ "First-diffs",
                        grepl("^g.l_edgar_v7", source) ~ "Growth rates"))

```

## Various country groupes {.tabset .tabset-fade .tabset-pills}

### groupby {.tabset .tabset-fade .tabset-pills}

```{r, include = FALSE}

gen_plots <- function(ct_sample, yr_range) { #for(y in c("1990:2021", "2000:2021")){
  for(p in c(0.01, 0.001))
    for(l in c(TRUE, FALSE)){
      for(b in c(30,20)){
      pl <- get_model(ct_sample, yr_range, p, l, b)
      print(pl$plot +
        ggtitle(label = pl$main_title, subtitle = pl$sub_title))
      print(pl$plot_grid +
        ggtitle(label = pl$main_title, subtitle = pl$sub_title))
      cat("\n")
    }
  }
}
#}

```

### EU15: 2000-2021

```{r, fig.height = 5, fig.width = 7, eval = FALSE, echo = FALSE, cache = TRUE}

gen_plots('EU15', "2000:2021")

```

### EU15: 1990-2021

```{r, fig.height = 5, fig.width = 7, eval = FALSE, echo = FALSE, cache = TRUE}

gen_plots('EU15', "1990:2021")

```


### EU31: 2000-2021

. . .

```{r, fig.height = 7, fig.width = 7,eval = FALSE, include = FALSE, cache = TRUE}

gen_plots('EU31', "2000:2021")

```



### EU31: 1990-2021

. . .

```{r, fig.height = 7, fig.width = 7, echo = FALSE, eval = FALSE, cache = TRUE}

gen_plots('EU31', "1990:2021")

```


### OECD: 2000-2021

. . .

```{r, fig.height = 7, fig.width = 7.5, echo = FALSE, eval = FALSE , cache = TRUE}

gen_plots('OECD', "2000:2021")

```


### OECD: 1990-2021

. . .

```{r, fig.height = 7, fig.width = 7.5, echo = FALSE, eval = FALSE, cache = TRUE}

gen_plots('OECD', "1990:2021")

```


### BRICS: 2000-2021

```{r, fig.height = 5, fig.width = 7, echo = FALSE, eval = FALSE, cache = TRUE}

gen_plots('BRICS', "2000:2021")

```

## Various country groupes {.tabset .tabset-fade .tabset-pills}

### Selected  EU15+ US, Canada, New Zealand, Australia, Switzerland, Japan

```{r, echo = FALSE, cache = TRUE}

gen_plots('EU15+selected', "2000:2021")

```

### Selected  EU15+ US, Canada, New Zealand, Australia, Switzerland, Japan

```{r, echo = FALSE,  cache = TRUE}

gen_plots('EU15+selected', "1990:2021")

```
